apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: ${ letsencrypt_email }

    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging

    # ACME DNS-01 provider configurations
    solvers:
      # Here we define a list of DNS-01 providers that can solve DNS challenges
      - dns01:
          cnameStrategy: Follow
          cloudflare:
            email: ${cloudflare_email}
            apiKeySecretRef:
              name: ${cloudflare_api_key_secret}
              key: apikey
        selector:
          dnsZones:
            - '${cloudflare_zone}'
          matchLabels:
            'use-cloudflare-solver': 'true'
        